{% set version = "3.5.1" %}

package:
  name: flit-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flit/flit-{{ version }}.tar.gz
  sha256: 2e3b7377714483ecc54b236330d7bf3467b9f5b909b22333b50b6b4324162510
  folder: source

build:
  noarch: python
  number: 0

# Specifying `python` as a top-level build requirements to force conda to
# render the recipe correctly
requirements:
  host:
    - python >=3.6

outputs:
  - name: flit-core
    version: {{ version }}
    build:
      script: python -m pip install --no-deps -vv source/flit_core/
      noarch: python
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - tomli
        - tomli-w
    test:
      imports:
        - flit_core
        - flit_core.common

  - name: flit
    version: {{ version }}
    build:
      script: cd source/ && FLIT_ROOT_INSTALL=1 python -m flit install --deps=none
      noarch: python
      entry_points:
        - flit = flit:main
    requirements:
      host:
        - python >=3.6
        - pip
        - docutils
        - requests
        - tomli
        - tomli-w
        - {{ pin_subpackage('flit-core', exact=True) }}
      run:
        - python >=3.6
        - pip
        - docutils
        - requests
        - tomli
        - tomli-w
        - {{ pin_subpackage('flit-core', exact=True) }}
    test:
      imports:
        - flit
      commands:
        - flit --version

about:
  home: https://flit.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: source/LICENSE
  summary: Simplified packaging of Python modules

extra:
  recipe-maintainers:
    - Carreau
    - minrk
    - takluyver
    - ocefpaf
